---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: behoyh/angular-firestore-kubernetes
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: blog-app